[package]
name = "qr-issuer"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
qrcode = "0.12.0"
image = "0.23.14"
hmac = "0.11.0"
sha2 = "0.9.5"
base64 = "0.13.0"
